export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';
export const GET_IMAGES_STARTED = 'GET_IMAGES_STARTED';
export const SET_IMAGE_VIEW_URL = 'SET_IMAGE_VIEW_URL';
